version: "3.9"
services:
  wp-app:
    build: "./requirements/wp/."
    image: wp-image:latest
    container_name: "wp-instance"
  webserver:
    build: "./requirements/nginx/."
    image: nginx-image:latest
    container_name: "nginx-instance"
    ports:
      - "443:443"
  database:
    build: "./requirements/mariadb/."
    image: mariadb-image:latest
    container_name: "mariadb-instance"

