user                            www;
worker_processes                auto; # it will be determinate automatically by the number of core

error_log                       /var/log/nginx/error.log warn;
pid                             /var/run/nginx/nginx.pid; # it permit you to use rc-service nginx reload|restart|stop|start

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           3;
	server {
		listen					443 ssl;
		server_name				www.example.com;
		
		ssl_certificate				/etc/nginx/ssl/my.crt;
		ssl_certificate_key			/etc/nginx/ssl/my.key;
		root                    /www;
        index                   index.html;
	}
    server {
        listen                  80;
		server_name				www.42.mandre.fr;
		return 301 https://$host$request_uri;
        }
}
